export TERM="xterm-256color"
export RCDIR=`realpath -m $(realpath $HOME/.zshrc)/../..`
export FZF_BASE="$RCDIR/vim/config/bundle/fzf"

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

autoload bashcompinit
bashcompinit

source "$RCDIR/zsh/antigen/antigen.zsh"

(
  command -v dircolors &> /dev/null && eval `dircolors "$RCDIR/zsh/dracula.dircolors"`
) || (
  command -v gdircolors &> /dev/null && eval `gdircolors "$RCDIR/zsh/dracula.dircolors"`
)

command -v ag >/dev/null 2>&1 && {
  export FZF_DEFAULT_COMMAND='ag -g "" --hidden --ignore-dir .git'
  export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
}

antigen use oh-my-zsh

antigen bundle command-not-found
antigen bundle git
antigen bundle gpg-agent
antigen bundle fzf
antigen bundle zdharma/fast-syntax-highlighting
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle zsh-users/zsh-completions
antigen bundle asdf

POWERLEVEL9K_MODE='nerdfont-complete'
POWERLEVEL9K_SHORTEN_STRATEGY='truncate_to_unique'
POWERLEVEL9K_SHORTEN_DIR_LENGTH=2
POWERLEVEL9K_VCS_SHORTEN_STRATEGY='truncate_from_right'
POWERLEVEL9K_VCS_SHORTEN_LENGTH=17
POWERLEVEL9K_VCS_SHORTEN_MIN_LENGTH=25
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(time dir asdf vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=()

antigen theme romkatv/powerlevel10k

antigen apply

if [ "$(uname 2> /dev/null)" != "Linux" ]; then
    command -v compaudit &> /dev/null && compaudit 2>&1 | grep --null '^/' -s | xargs -0 chmod 755
else
    command -v compaudit &> /dev/null && compaudit 2>&1 | grep -z '^/' -s | xargs -0r chmod 755
fi

alias vim=vim -p

function vimgrep() {
  vim -p $(git grep $@ | cut -d: -f1 | sort | uniq)
}

[[ -f "$RCDIR/env" ]] && source "$RCDIR/env"

export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
[[ -d "$HOME/Library/Python/3.7/bin" ]] && export PATH="$PATH:$HOME/Library/Python/3.7/bin"

[[ -f "/usr/bin/keychain" ]] && [[ -z "/usr/bin/keychain" ]] && /usr/bin/keychain --quiet --nogui $HOME/.ssh/id_rsa
[[ -f "$HOME/.keychain/$HOST-sh" ]] && source $HOME/.keychain/$HOST-sh

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# NVM (node) setup -- disabled in favor of asdf
# export NVM_DIR="$HOME/.nvm"
# [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
# source "$RCDIR/zsh/nvm.zsh"
# [ -s "/usr/local/opt/nvm/etc/bash_completion" ] && . "/usr/local/opt/nvm/etc/bash_completion"  # This loads nvm bash_completion

# YVM (yarn) setup -- disabled in favor of asdf
# export YVM_DIR=/home/rintaun/.yvm
# [ -r $YVM_DIR/yvm.sh ] && . $YVM_DIR/yvm.sh

# RVM (ruby) setup -- disabled in favor of asdf
# export PATH="$PATH:$HOME/.rvm/bin"
# [[ -s "~/.rvm/scripts/rvm" ]] && source ~/.rvm/scripts/rvm

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

setopt histignorespace
