source ~/.rc.d/zsh/antigen.zsh

RCDIR=`realpath .zshrc`/../../

export FZF_BASE="${RCDIR:A}/vim/config/bundle/fzf"

antigen use oh-my-zsh

antigen bundle command-not-found
antigen bundle git
antigen bundle gpg-agent
antigen bundle fzf
antigen bundle zdharma/fast-syntax-highlighting
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle zsh-users/zsh-completions

POWERLEVEL9K_MODE='nerdfont-complete'
POWERLEVEL9K_SHORTEN_STRATEGY='truncate_to_unique'
POWERLEVEL9K_SHORTEN_DIR_LENGTH=2
POWERLEVEL9K_VCS_SHORTEN_STRATEGY='truncate_from_right'
POWERLEVEL9K_VCS_SHORTEN_LENGTH=17
POWERLEVEL9K_VCS_SHORTEN_MIN_LENGTH=25
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(time dir rvm nvm vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=()

antigen theme bhilburn/powerlevel9k

antigen apply

alias vim=vim -p

function vimgrep() {
  vim -p $(git grep $@ | cut -d: -f1 | sort | uniq)
}

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"

