source ~/.rc.d/zsh/antigen.zsh

antigen use oh-my-zsh

antigen bundle command-not-found
antigen bundle git
antigen bundle gpg-agent
antigen bundle zdharma/fast-syntax-highlighting
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle zsh-users/zsh-completions

POWERLEVEL9K_MODE='awesome-patched'
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(time dir rvm nvm vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=()

antigen theme bhilburn/powerlevel9k

antigen apply
